# # version: '3.8'

# # services:
# #   couchdb:
# #     image: couchdb:3.3
# #     container_name: couchdb_container
# #     restart: always
# #     ports:
# #       - "5984:5984"
# #     environment:
# #       - COUCHDB_USER=hyrumsapurco27
# #       - COUCHDB_PASSWORD=July272002!
# #     volumes:
# #       - couchdb_data:/opt/couchdb/data

# #   backend:
# #     build:
# #       context: ./backend
# #     container_name: nodejs_backend
# #     restart: always
# #     depends_on:
# #       - couchdb
# #     ports:
# #       - "3000:3000"
# #     environment:
# #       - COUCHDB_URL=http://hyrumsapurco27:July272002!@couchdb:5984
# #     volumes:
# #       - ./backend:/app

# #   frontend:
# #     build:
# #       context: ./angular19Tutorial
# #     container_name: angular_frontend
# #     restart: always
# #     depends_on:
# #       - backend
# #     ports:
# #       - "80:80"
# #     volumes:
# #       - ./angular19Tutorial:/app

# # volumes:
# #   couchdb_data:

# version: '3.8'

# services:
#   angular19tutorial:
#     build: ./angular19Tutorial
#     ports:
#       - "8080:80"
#     networks:
#       - app-network
#     restart: always

#   backend:
#     build: ./backend
#     ports:
#       - "3000:3000"
#     environment:
#       - COUCHDB_URL=http://hyrumsapurco27:July272002!@couchdb:5984
#     depends_on:
#       couchdb:
#         condition: service_healthy
#     networks:
#       - app-network
#     restart: always

#   couchdb:
#     image: couchdb:3.2
#     ports:
#       - "5984:5984"
#     environment:
#       - COUCHDB_USER=hyrumsapurco27
#       - COUCHDB_PASSWORD=July272002!
#     networks:
#       - app-network
#     restart: always
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://hyrumsapurco27:July272002!@couchdb:5984/_all_dbs"]
#       interval: 5s
#       retries: 5

# networks:
#   app-network:
#     driver: bridge





version: "3.8"
services:
  angular:
    build: ./angular19Tutorial
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - COUCHDB_URL=http://hyrumsapurco27:July272002@couchdb:5984
    depends_on:
      - couchdb

  couchdb:
    image: couchdb:3
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=hyrumsapurco27
      - COUCHDB_PASSWORD=July272002
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:
